"""Main cerebra class
"""

import logging
import os.path as op
from appdirs import user_cache_dir
import numpy as np
from .data import CerebraData
from .data._transforms import (
    lia_points_to_ras_points,
    point_cloud_to_voxel,
    merge_voxel_grids,
)
from .plotting.plotting_2d import orthoview, plot_brain_slice_2d, figure_features
from .plotting.colors import normalize_colors_input
from .cerebra_mne import MNE, MontageMNE
from typing import Dict, Tuple, TypedDict, List, Union
from typing_extensions import Unpack

logger = logging.getLogger(__name__)

ColorType = Union[
    List[str],
    List[Tuple[float, float, float]],
    str,
    Tuple[float, float, float],
    None,
]


class Plot3DArgs(TypedDict, total=False):
    """
    colors can be in hex format (#ff00ff) and tuple format ranging 0-1 ((1,0,1)).
    Can be a single value to create a uniformly colored brain, and can be of length
    src_space_labels to assign a different color to every point in the source space.
    Defaults to None (default color -- regions colored).
    """

    plot_src_space: bool | None
    """
    Whether to plot the source space or not. Defaults to True.
    """


class CerebrA(CerebraData, MNE):
    """
    CerebrA class inherits from CerebraData, Plotting, and MNE classes.
    This class provides methods to handle brain data, perform plotting,
    and manage MNE functionalities.
    """

    def __init__(
        self,
        montage_name: str | None = None,
        head_size: float | None = None,
        cache_path: str | None = None,
        source_space_grid_size: int = 3,
        source_space_include_wm: bool = False,
        source_space_include_non_cortical: bool = False,
        bem_conductivity: Tuple[float, float, float] = (0.33, 0.0042, 0.33),
        bem_ico: int = 4,
        tex: bool = True,
        font: str = "serif",
        dpi: int = 180,
    ):
        """
        Main init function for CerebrA

        Args:
            montage_name (str, optional): Montage name, required to build the forward model.
                Can be set after initialization using cerebra.montage_name. Defaults to None.
            head_size (float, optional): Head size, required to build the forward model.
                Can be set after initialization using cerebra.head_size. Defaults to None.
            cache_path (str, optional): Cache path to use for files generated by
                CerebrA. If None use default system default cache path. Defaults to None.
            source_space_grid_size (int, optional): Grid size for generating the source space,
                bigger means more downsampling (less src space points). Defaults to 3.
            source_space_include_wm (bool, optional): Whether to include whitematter
                in the source space. Defaults to False.
            source_space_include_non_cortical (bool, optional): Whether to include non-cortical
                regions in the source space. Defaults to False.
            bem_conductivity (Tuple[float, float, float], optional): Bem conductivity. Defaults to (0.33, 0.0042, 0.33).
            bem_ico (int, optional): BEM resolution (triangles). Defaults to 4.
            tex (bool, optional): Use latex for figures (should be installed locally)
        """
        # Cache path
        if cache_path is None:
            self.cache_path = op.join(user_cache_dir("cerebra_atlas_python"), "cerebra")
        else:
            self.cache_path = cache_path

        # Init cerebra data (brain image, csv metadata and Freesurfer data)
        CerebraData.__init__(self, cache_path=self.cache_path)
        logger.debug("INIT CerebraData")

        self.montage_name = montage_name
        self.head_size = head_size
        # CerebraData should be initialized before MNE
        MNE.__init__(
            self,
            cache_path=self.cache_path,
            cerebra_data=self,
            source_space_grid_size=source_space_grid_size,
            source_space_include_wm=source_space_include_wm,
            source_space_include_non_cortical=source_space_include_non_cortical,
            bem_conductivity=bem_conductivity,
            bem_ico=bem_ico,
        )
        logger.debug("INIT MNE")
        figure_features(tex=tex, font=font, dpi=dpi)
        # CerebraData and MNE should be initialized before Plotting
        # Plotting.__init__(self)
        # logger.debug("INIT Plotting")

    @property
    def montage_name(self) -> str | None:
        """Montage name. May be set using cerebra.montage_name.
        Montage names should be included in downsampled_montages.py.
        Corregistration should be manually made for a new montage + head size
        before calling cerebra.get_forward()

        Returns:
            str: montage name
        """
        return self._montage_name

    @montage_name.setter
    def montage_name(self, _montage_name: str | None):
        if _montage_name is None:
            self._montage_name = _montage_name
            return
        assert (
            _montage_name in MontageMNE.montage_names
        ), f"Montage {_montage_name} not found. Available montages: {MontageMNE.montage_names}"
        self._montage_name = _montage_name

    @property
    def head_size(self) -> float | None:
        """Head size. Used to build the forward model.
        Head size is used along montage_name to determine electrode
        positions and transformations. Corregistration should be manually
        made for a new montage  + head size  before calling cerebra.get_forward()

        Returns:
            float: head size
        """
        return self._head_size

    @head_size.setter
    def head_size(self, _head_size: float | None):
        self._head_size = _head_size

    def get_src_space_points(self):
        """Returns a np array of src space points in RAS space.
        Values ranging 0-255 representing position in space.

        Returns:
            np.ndarray: source space points (RAS) numpy array.
        """
        return self.src_space_points

    def get_src_space_labels(self):
        """Returns a np array of len(src_space_points).
        Values ranging 0-64 represent cortical ids

        Returns:
            np.ndarray: source space labels numpy array.
        """
        return self.src_space_labels

    def plot_2d(
        self,
        kind: str = "single",
        axis: int = 0,
        fixed_value: int | None = None,
        plot_regions: bool = True,
        plot_whitematter: bool = False,
        plot_empty: bool = False,
        plot_affine: bool = False,
        affine_color: str = "#ccc",
        plot_coordinate_frame_info: bool = False,
        coordinate_frame_info_text_size: int = 14,
        plot_relative_positions: bool = True,
        relative_positions_text_size: int = 12,
        plot_axes: bool = True,
        plot_axis_labels: bool = True,
        ax_label_text_size=8,
        plot_grid: bool = False,
        plot_narrow_ax: bool = True,
        plot_legend: bool = False,
        cmap_name: str = "default",
        volume_colors: List[int] | None = None,
        pt: List[int] | None = None,
        pt_text: str | None = None,
        pt_text_size: int = 8,
        plot_pt_lines: bool = True,
        # plot_region_names=False,
        # region_names_text_size=14,
        # src_space_points=None,
        # bem_volume=None,
        # highlighted_region_ids=None,
        # highlighted_region_names=None,
        # highlighted_region_centroids=None,
        # highlighted_cortical_ids=None,
        # region_centroid=None,
        # pt_dist=None,
        # t1_volume=None,
        title=None,
        title_size=35,
        fig=None,
        ax=None,
        axs=None,
        figsize=None,
    ):
        """
        Plot a brain volume slice in 2D using the RAS coordinate frame.

        Args:
            kind (str, optional): "single" or "orthoview". Defaults to "single".
            axis (int, optional): Axis to show in plot, either 0=X, 1=Y, 2=Z. Unused if
                kind = "orthoview". Defaults to 0.
            fixed_value (int, optional): Value between 0 and 255 that defines the fixed value
                for the plane that is drawn. If not provided then the affine is used. Unused if
                kind = "orthoview". Defaults to None.
            plot_regions (bool, optional): Plot the region data. Defaults to True.
            plot_whitematter (bool, optional): Plot whitematter. Unused if plot_regions=False.
            Defaults to False.
            plot_empty (bool, optional): Paint empty space (label 0 in voxel grid) black.
                Defaults to False (White).
            plot_affine (bool, optional): Plot affine matrix. Defaults to False.
            affine_color (str, optional): Affine matrix color (hex). Defaults to #ccc.

            title (str, optional): Axis title. Unused if kind="orthoview". Defaults to None.
            title_size (int, optional): Title size. Unused if title is None. Defaults to 35.
            fig (matplotlib.pyplot.figure, optional): Matplotlib figure to use for plotting.
                If not provided then create default figure. Should be accompanied by either
                ax or axs. Defaults to None.
            ax (matplotlib.pyplot.axis, optional): matplotlib axis. Unused if
                kind = "orthoview". Defaults to None.
            axs (_type_, optional): matplotlib multiple axes for orthoview plot,
                Unused if kind = "single". Defaults to None.
            figsize (tuple, optional): Matplotlib figsize. Defaults to None.

        Returns:
            fig,ax | fig,axs: Returns matplotlib figure along with
            axis (kind="single") or axes (kind="orthoview")
        """
        # Check parameters
        assert kind in [
            "single",
            "orthoview",
        ], f"Wrong kind value, 2d plot can be single or orthoview"

        assert axis in [0, 1, 2], f"Wrong axis value,should be 0,1 or 2"

        # Prepare plot data
        plot_data = self._prepare_plot_data()

        # Create shared args between the 2 plot functions
        shared_args = {
            "_plot_data": plot_data,
            "fig": fig,
            "plot_regions": plot_regions,
            "plot_whitematter": plot_whitematter,
            "plot_empty": plot_empty,
            "plot_affine": plot_affine,
            "affine_color": affine_color,
            "figsize": figsize,
            "plot_coordinate_frame_info": plot_coordinate_frame_info,
            "coordinate_frame_info_text_size": coordinate_frame_info_text_size,
            "plot_relative_positions": plot_relative_positions,
            "relative_positions_text_size": relative_positions_text_size,
            "plot_axes": plot_axes,
            "plot_axis_labels": plot_axis_labels,
            "ax_label_text_size": ax_label_text_size,
            "plot_grid": plot_grid,
            "plot_narrow_ax": plot_narrow_ax,
            "plot_legend": plot_legend,
            "cmap_name": cmap_name,
            "volume_colors": volume_colors,
            "pt": pt,
            "pt_text": pt_text,
            "pt_text_size": pt_text_size,
            "plot_pt_lines": plot_pt_lines,
        }

        # Plot
        if kind == "single":
            fig, ax = plot_brain_slice_2d(
                **shared_args,
                ax=ax,
                axis=axis,
                fixed_value=fixed_value,
                title=title,
                title_size=title_size,
            )
            return fig, ax
        elif kind == "orthoview":
            fig, axs = orthoview(**shared_args, axs=axs)
            return fig, axs

    # def plot_3d(
    #     self,
    #     rotate_mode=1,
    #     save_path=None,
    #     update_fn=None,
    #     **kwargs: Unpack[Plot3DArgs],
    # ):
    #     """Plot 3D brain"""
    #     plot_data_ = {
    #         "rotate_mode": rotate_mode,
    #         "save_path": save_path,
    #         "update_fn": update_fn,
    #     }
    #     self._plot(kind="3d", plot_data_=plot_data_, **kwargs)

    def _prepare_plot_data(self, colors=None, _plot_data=None):
        # Prepare plot data
        plot_data = {
            "affine": self.affine,
            "cerebra_volume": self.cerebra_volume,
            "src_space_points": self.src_space_points,
            "src_space_labels": self.src_space_labels,
            "bem_vertices_vox_ras": self._get_bem_vertices_vox_ras(),
            "bem_normals_vox_ras": self._get_bem_normals_vox_ras(),
            "bem_triangles": self.get_bem_triangles(),
            "info": (
                self.info
                if (self.montage_name is not None and self.head_size is not None)
                else None
            ),
            "fiducials": self.fiducials,
        }
        if _plot_data is not None:
            plot_data = {**plot_data, **_plot_data}
        plot_data["colors"] = normalize_colors_input(len(self.src_space_labels), colors)
        return plot_data

    def _get_bem_vertices_vox_lia(self):
        return np.array(
            [self.apply_mri_vox_t(layer) for layer in self.get_bem_vertices_mri()]
        )

    def _get_bem_normals_vox_lia(self):
        return np.array(
            [self.apply_mri_vox_t(layer) for layer in self.get_bem_normals_mri()]
        )

    def _get_bem_vertices_vox_ras(self):
        return np.array(
            [
                lia_points_to_ras_points(layer)
                for layer in self._get_bem_vertices_vox_lia()
            ]
        )

    def _get_bem_normals_vox_ras(self):
        return np.array(
            [
                lia_points_to_ras_points(layer)
                for layer in self._get_bem_normals_vox_lia()
            ]
        )

    def _get_bem_volume_ras(self, include_layers=[0, 1, 2]) -> np.ndarray:
        for i, layer_pts in enumerate(self.get_bem_vertices_mri()[include_layers]):
            layer_pts = self.apply_mri_vox_t(layer_pts)
            layer_pts = lia_points_to_ras_points(layer_pts)
            layer_vol = point_cloud_to_voxel(layer_pts, vox_value=i + 1)
            if i == 0:
                volume = layer_vol
            else:
                volume = merge_voxel_grids(volume, layer_vol)  # type: ignore
        return volume  # type: ignore


if __name__ == "__main__":
    cerebra = CerebrA()
