"""Main cerebra class
"""

import logging
import os.path as op
from appdirs import user_cache_dir
import numpy as np
from .data import CerebraData
from .data._transforms import (
    lia_points_to_ras_points,
    point_cloud_to_voxel,
    merge_voxel_grids,
)
from .plotting.plotting_2d import orthoview, plot_brain_slice_2d, figure_features
from .plotting.colors import normalize_colors_input
from .cerebra_mne import MNE, MontageMNE
from typing import Dict, Tuple, TypedDict, List, Union
from typing_extensions import Unpack

logger = logging.getLogger(__name__)


class Plot3DArgs(TypedDict, total=False):
    colors: Union[
        List[str],
        List[Tuple[float, float, float]],
        str,
        Tuple[float, float, float],
        None,
    ]
    """
    colors can be in hex format (#ff00ff) and tuple format ranging 0-1 ((1,0,1)).
    Can be a single value to create a uniformly colored brain, and can be of length 
    src_space_labels to assign a different color to every point in the source space.
    Defaults to None (default color -- regions colored).
    """

    plot_src_space: bool | None
    """
    Whether to plot the source space or not. Defaults to True.
    """


class CerebrA(CerebraData, MNE):
    """
    CerebrA class inherits from CerebraData, Plotting, and MNE classes.
    This class provides methods to handle brain data, perform plotting,
    and manage MNE functionalities.
    """

    def __init__(
        self,
        montage_name: str | None = None,
        head_size: float | None = None,
        cache_path: str | None = None,
        source_space_grid_size: int = 3,
        source_space_include_wm: bool = False,
        source_space_include_non_cortical: bool = False,
        bem_conductivity: Tuple[float, float, float] = (0.33, 0.0042, 0.33),
        bem_ico: int = 4,
        tex: bool = True,
        font: str = "serif",
        dpi: int = 180,
    ):
        """
        Main init function for CerebrA

        Args:
            montage_name (str, optional): Montage name, required to build the forward model.
                Can be set later using cerebra.montage_name. Defaults to None.
            head_size (float, optional): Head size, required to build the forward model.
                Can be set later using cerebra.head_size. Defaults to None.
            cache_path (str, optional): Cache path to use for files generated by
                CerebrA. If None use default system default cache path. Defaults to None.
            source_space_grid_size (int, optional): Grid size for generating the source space,
                bigger means more downsampling (less src space points). Defaults to 3.
            source_space_include_wm (bool, optional): Whether to include whitematter
                in the source space. Defaults to False.
            source_space_include_non_cortical (bool, optional): Whether to include non-cortical
                regions in the source space. Defaults to False.
            bem_conductivity (Tuple[float, float, float], optional): Bem conductivity. Defaults to (0.33, 0.0042, 0.33).
            bem_ico (int, optional): BEM resolution (triangles). Defaults to 4.
            tex (bool, optional): Use latex for figures (should be installed locally)
        """
        # Cache path
        if cache_path is None:
            self.cache_path = op.join(user_cache_dir("cerebra_atlas_python"), "cerebra")
        else:
            self.cache_path = cache_path

        # Init cerebra data (brain image, csv metadata and Freesurfer data)
        CerebraData.__init__(self, cache_path=self.cache_path)
        logger.debug("INIT CerebraData")

        self.montage_name = montage_name
        self.head_size = head_size
        # CerebraData should be initialized before MNE
        MNE.__init__(
            self,
            cache_path=self.cache_path,
            cerebra_data=self,
            source_space_grid_size=source_space_grid_size,
            source_space_include_wm=source_space_include_wm,
            source_space_include_non_cortical=source_space_include_non_cortical,
            bem_conductivity=bem_conductivity,
            bem_ico=bem_ico,
        )
        logger.debug("INIT MNE")
        figure_features(tex=tex, font=font, dpi=dpi)
        # CerebraData and MNE should be initialized before Plotting
        # Plotting.__init__(self)
        # logger.debug("INIT Plotting")

    @property
    def montage_name(self) -> str | None:
        """Montage name. May be set using cerebra.montage_name.
        Montage names should be included in downsampled_montages.py.
        Corregistration should be manually made for a new montage + head size
        before calling cerebra.get_forward()

        Returns:
            str: montage name
        """
        return self._montage_name

    @montage_name.setter
    def montage_name(self, _montage_name: str | None):
        if _montage_name is None:
            self._montage_name = _montage_name
            return
        assert (
            _montage_name in MontageMNE.montage_names
        ), f"Montage {_montage_name} not found. Available montages: {MontageMNE.montage_names}"
        self._montage_name = _montage_name

    @property
    def head_size(self) -> float | None:
        """Head size. Used to build the forward model.
        Head size is used along montage_name to determine electrode
        positions and transformations. Corregistration should be manually
        made for a new montage  + head size  before calling cerebra.get_forward()

        Returns:
            float: head size
        """
        return self._head_size

    @head_size.setter
    def head_size(self, _head_size: float | None):
        self._head_size = _head_size

    def get_src_space_points(self):
        """Returns a np array of src space points in RAS space.
        Values ranging 0-255 representing position in space.

        Returns:
            np.ndarray: source space points (RAS) numpy array.
        """
        return self.src_space_points

    def get_src_space_labels(self):
        """Returns a np array of len(src_space_points).
        Values ranging 0-64 represent cortical ids

        Returns:
            np.ndarray: source space labels numpy array.
        """
        return self.src_space_labels

    def plot_2d(self, kind="single", show=True):
        """
        See :class:`cerebra_atlas_python.plotting.plotting_2d.Plots2D`.
        """
        # Check parameters
        allowed_2d_plot_kinds = ["single", "orthoview"]
        assert (
            kind in allowed_2d_plot_kinds
        ), f"Wrong kind value, 2d plot can be {' '.join(allowed_2d_plot_kinds)}"

        # Prepare plot data
        plot_data = self._prepare_plot_data()

        # Plot
        if kind == "single":
            fig, ax = plot_brain_slice_2d(plot_data)
            return fig, ax
        elif kind == "orthoview":
            fig, axs = orthoview(_plot_data=plot_data)
            return fig, axs

    # def orthoview(self, **kwargs):
    #     """Plot 2D brain with orthoview"""
    #     self._plot(kind="orthoview", **kwargs)

    # def plot_3d(
    #     self,
    #     rotate_mode=1,
    #     save_path=None,
    #     update_fn=None,
    #     **kwargs: Unpack[Plot3DArgs],
    # ):
    #     """Plot 3D brain"""
    #     plot_data_ = {
    #         "rotate_mode": rotate_mode,
    #         "save_path": save_path,
    #         "update_fn": update_fn,
    #     }
    #     self._plot(kind="3d", plot_data_=plot_data_, **kwargs)

    def _prepare_plot_data(self, colors=None, _plot_data=None):
        # Prepare plot data
        plot_data = {
            "affine": self.affine,
            "cerebra_volume": self.cerebra_volume,
            "src_space_points": self.src_space_points,
            "src_space_labels": self.src_space_labels,
            "bem_vertices_vox_ras": self._get_bem_vertices_vox_ras(),
            "bem_normals_vox_ras": self._get_bem_normals_vox_ras(),
            "bem_triangles": self.get_bem_triangles(),
            "info": (
                self.info
                if (self.montage_name is not None and self.head_size is not None)
                else None
            ),
            "fiducials": self.fiducials,
        }
        if _plot_data is not None:
            plot_data = {**plot_data, **_plot_data}
        plot_data["colors"] = normalize_colors_input(len(self.src_space_labels), colors)
        return plot_data

    def _get_bem_vertices_vox_lia(self):
        return np.array(
            [self.apply_mri_vox_t(layer) for layer in self.get_bem_vertices_mri()]
        )

    def _get_bem_normals_vox_lia(self):
        return np.array(
            [self.apply_mri_vox_t(layer) for layer in self.get_bem_normals_mri()]
        )

    def _get_bem_vertices_vox_ras(self):
        return np.array(
            [
                lia_points_to_ras_points(layer)
                for layer in self._get_bem_vertices_vox_lia()
            ]
        )

    def _get_bem_normals_vox_ras(self):
        return np.array(
            [
                lia_points_to_ras_points(layer)
                for layer in self._get_bem_normals_vox_lia()
            ]
        )

    def _get_bem_volume_ras(self, include_layers=[0, 1, 2]) -> np.ndarray:
        for i, layer_pts in enumerate(self.get_bem_vertices_mri()[include_layers]):
            layer_pts = self.apply_mri_vox_t(layer_pts)
            layer_pts = lia_points_to_ras_points(layer_pts)
            layer_vol = point_cloud_to_voxel(layer_pts, vox_value=i + 1)
            if i == 0:
                volume = layer_vol
            else:
                volume = merge_voxel_grids(volume, layer_vol)  # type: ignore
        return volume  # type: ignore


if __name__ == "__main__":
    cerebra = CerebrA()
    cerebra.corregistration()
